### ISSUE TITLE
Coffee-script error since 1.3.1

### ISSUE THREAD

**Issue by redbugz** [wright-io/givenwhenthen#4] opened 2012-07-14 06:42 UTC
It looks like a change in coffee-script 1.3.1 causes acceptance.coffee to no longer compile correctly:

Error: In /Users/allredlt/projects/node/givenwhenthen/lib/acceptance.coffee, the variable "steps" can't be assigned with ?= because it has not been defined.
    at Assign.compileConditional (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:1670:15)
    at Assign.compileNode (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:1532:23)
    at Assign.compile (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:46:21)
    at Block.compileNode (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:307:23)
    at Block.compileWithDeclarations (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:391:19)
    at Code.compileNode (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:1836:35)
    at Code.compile (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:46:21)
    at Assign.compileNode (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:1554:24)
    at Assign.compile (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:46:21)
    at Block.compileNode (/Users/allredlt/projects/node/givenwhenthen/node_modules/coffee-script/lib/coffee-script/nodes.js:307:23)

I saw a note in the coffee-script release notes that ?= changed in 1.3.1 to fail if the variable does not exist in the current scope

**Comment by ghost** [comment] 2012-10-26 20:27
I'm seeing this too.

**Comment by esques** [comment] 2012-12-16 07:30
confirm

**Comment by ghost** [comment] 2012-12-16 09:39
This should be fixed now with the latest version

**Comment by esques** [comment] 2012-12-16 11:37
Great. Thank you
Am 16.12.2012 10:39 schrieb "Robert Quinlivan" notifications@github.com:

**Comment by esques** [comment] 2012-12-16 14:48
c:\Users\roland
├── coffee-script@1.4.0
├─┬ givenwhenthen@0.1.0

$ cake

C:\Users\roland\node_modules\givenwhenthen\node_modules\coffee-script\lib\coffee
-script\coffee-script.js:55
      throw err;
            ^
Error: In C:\Users\roland\node_modules\givenwhenthen\lib\acceptance.coffee, the
variable "steps" can't be assigned with ?= because it has not been defined.
    at Assign.exports.Assign.Assign.compileConditional (C:\Users\roland\node_mod
ules\givenwhenthen\node_modules\coffee-script\lib\coffee-script\nodes.js:1655:15

**Comment by esques** [comment] 2012-12-16 15:39
Aha! On Linux it shows me that my nodejs version is to new!
You only support  nodejs <0.5.0

**Comment by ghost** [comment] 2012-12-22 18:02
The cake file appears to be broken at the moment. I'm using `npm test` to run the specs for this repo. If you are seeing a problem with your platform, can you please write a regression guard for it? That'll make it easier for us to figure out what your issue is. Thanks

**Comment by mnshah** [comment] 2013-02-26 00:53
I get the same errors.  I believe its related to this change made in coffee-script 1.3.1 in April 2012 : 

"Conditional assignment of previously undefined variables  a or= b is now considered a syntax error."

I'm running coffee-script 1.5, Node 0.8.10, and request 2.14.0.  Is any work-around to this? I'd like to get this set up to run on Sauce.

**Comment by wright-io** [comment] 2013-02-28 18:31
Resolved.

**Closed as completed by wright-io** 2013-02-28 18:31 UTC
